create extension if not exists pgcrypto;

create table if not exists public.restaurant_settings (
  singleton boolean primary key default true,
  name text not null,
  whatsapp text not null,
  base_url text not null,
  primary_color text not null default '#d92d48',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.menu_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  description text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.menu_products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  price integer not null check (price >= 0),
  category_name text not null references public.menu_categories(name) on update cascade,
  image_url text,
  available boolean not null default true,
  featured boolean not null default false,
  vegetarian boolean not null default false,
  prep_time integer not null default 15 check (prep_time > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.restaurant_tables (
  id uuid primary key default gen_random_uuid(),
  label text not null unique,
  slug text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  number bigint generated by default as identity unique,
  table_id uuid references public.restaurant_tables(id) on delete set null,
  table_label text not null,
  order_type text not null default 'Comer en el local',
  note text,
  subtotal integer not null default 0 check (subtotal >= 0),
  discount integer not null default 0 check (discount >= 0),
  tip_amount integer not null default 0 check (tip_amount >= 0),
  total integer not null default 0 check (total >= 0),
  status text not null default 'Pendiente'
    check (status in ('Pendiente', 'En preparación', 'Listo', 'Entregado', 'Cancelado')),
  whatsapp_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.menu_products(id) on delete set null,
  product_name text not null,
  unit_price integer not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0),
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists idx_menu_products_category_name on public.menu_products(category_name);
create index if not exists idx_orders_status on public.orders(status);
create index if not exists idx_orders_created_at on public.orders(created_at desc);
create index if not exists idx_order_items_order_id on public.order_items(order_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_restaurant_settings_updated_at on public.restaurant_settings;
create trigger trg_restaurant_settings_updated_at
before update on public.restaurant_settings
for each row execute function public.set_updated_at();

drop trigger if exists trg_menu_products_updated_at on public.menu_products;
create trigger trg_menu_products_updated_at
before update on public.menu_products
for each row execute function public.set_updated_at();

drop trigger if exists trg_orders_updated_at on public.orders;
create trigger trg_orders_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

alter table public.restaurant_settings enable row level security;
alter table public.menu_categories enable row level security;
alter table public.menu_products enable row level security;
alter table public.restaurant_tables enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "public restaurant_settings all" on public.restaurant_settings;
create policy "public restaurant_settings all"
on public.restaurant_settings
for all
to anon
using (true)
with check (true);

drop policy if exists "public menu_categories all" on public.menu_categories;
create policy "public menu_categories all"
on public.menu_categories
for all
to anon
using (true)
with check (true);

drop policy if exists "public menu_products all" on public.menu_products;
create policy "public menu_products all"
on public.menu_products
for all
to anon
using (true)
with check (true);

drop policy if exists "public restaurant_tables all" on public.restaurant_tables;
create policy "public restaurant_tables all"
on public.restaurant_tables
for all
to anon
using (true)
with check (true);

drop policy if exists "public orders all" on public.orders;
create policy "public orders all"
on public.orders
for all
to anon
using (true)
with check (true);

drop policy if exists "public order_items all" on public.order_items;
create policy "public order_items all"
on public.order_items
for all
to anon
using (true)
with check (true);
